Plannr/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plannr.Models;
using WebMatrix.WebData;
using System.Web.Security;
using Plannr.DAL;
using Plannr.Filters;
using Newtonsoft.Json;
using System.Web.Script.Serialization;

namespace Plannr.Controllers
{
    [Authorize(Roles = "Enseignant")]
    [InitializeSimpleMembership]
    public class BookController : Controller
    {   
        // Repository as private member, generic interface type
        private IDemandesRepository repository;
        private IEnseignementsRepository enseignementsRepository;
        private ICreneauxHorairesRepository creneauxHorairesRepository;

        // Constructor
        public BookController()
        {
            // Share same context for both repo
            var context = new PlannrContext();
            this.repository = new DemandesRepository(context);
            this.enseignementsRepository = new EnseignementsRepository(context);
            this.creneauxHorairesRepository = new CreneauxHorairesRepository(context);

        }

        // Give it as a parameter aswel for unit testing
        public BookController(IDemandesRepository repo, IEnseignementsRepository ensRepo, ICreneauxHorairesRepository crRepo)
        {
            this.repository = repo;
            this.enseignementsRepository = ensRepo;
            this.creneauxHorairesRepository = crRepo;
        }


        // GET: /Book/

      
        public ActionResult Index() {

            var id = (int) Membership.GetUser().ProviderUserKey;
            IEnumerable<DemandeReservation> demandes = this.repository.GetReservationsBy(id).ToList();


            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;

            ViewBag.JSONModel = JsonConvert.SerializeObject(demandes, Formatting.None, jsSettings);


            // Render full or partial.
            if (!Request.IsAjaxRequest())
            {
                return View(demandes);
            }
            else
            {
                return PartialView("_Index", demandes);
            }
        }


        //
        // GET: /Book/Create


        public ActionResult Create()
        {
            // Get Session from Current Logged User
            var id = (int)Membership.GetUser().ProviderUserKey;
            // On va chercher les enseignements qui sont attribués à l'enseignant pour les lister dans la DropList en sélectionner un, on le passe à la vue pour génrer la ListBox
            ViewBag.listEnseignements = this.enseignementsRepository.GetEnseignementsForTeacher(id);
            ViewBag.listCreneauxHoraires = this.creneauxHorairesRepository.getCreneauxHoraires();

            if (!Request.IsAjaxRequest())
            {
                return View();
            }
            else
            {
                return PartialView("_Create");
            }
        }

        //
        // POST: /Book/Create

        [HttpPost]
        public ActionResult Create(DemandeReservation demandereservation) {
            
            demandereservation.DateDemande = DateTime.Now;
            demandereservation.Checked = false;
            demandereservation.CheckedByTeacher = false;
            // Mapping
            demandereservation.Enseignement = this.enseignementsRepository.Get(demandereservation.Enseignement.Id);
            demandereservation.CreneauSouhaite = this.creneauxHorairesRepository.Find(demandereservation.CreneauSouhaite.Id);
            

            if (ModelState.IsValid)
            {
                repository.Insert(demandereservation);
                repository.Save();

                return RedirectToAction("Index");
            }

            //ModelState.Values.Where(modelState => modelState.Errors.Count > 0).ToList().ForEach(x => x.Errors.ToList().ForEach(y => System.Diagnostics.Debug.WriteLine(y.ErrorMessage)));


            // Since it's returing view, we need the listEnseignements in the ViewBag aswell
            var id = (int)Membership.GetUser().ProviderUserKey;
            ViewBag.listEnseignements = this.enseignementsRepository.GetEnseignementsForTeacher(id);
            ViewBag.listCreneauxHoraires = this.creneauxHorairesRepository.getCreneauxHoraires();

 

            return View(demandereservation);
        }

  
        //
        // GET: /Book/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DemandeReservation demandereservation = this.repository.Find(id);
            if (demandereservation == null)
            {
                return HttpNotFound();
            }
            return View(demandereservation);
        }

        //
        // POST: /Book/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var demande = this.repository.Find(id);

            if (demande.ReservationAssociee != null)
            {
                // On ne supprime pas une demande qui a déjà été validée.
                return new HttpStatusCodeResult(403);
            }

            // On vérifie que la demande existe.
            if (demande == null)
            {
                return new HttpStatusCodeResult(404);
            }

            var SessionId = (int)Membership.GetUser().ProviderUserKey;
            if (demande.Enseignement.Enseignant.UserId != SessionId)
            {
                return new HttpStatusCodeResult(403);
            }

            this.repository.Delete(id);
            this.repository.Save();
            if (!Request.IsAjaxRequest())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return new HttpStatusCodeResult(200);
            }
        }

    }
}

Plannr/Views/Book/Create.cshtml
@model Plannr.Models.DemandeReservation

@{
    ViewBag.Title = "Create";
}


@Html.Partial("_Create",Model);

Plannr/Views/Book/Delete.cshtml
@model Plannr.Models.DemandeReservation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>DemandeReservation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateDemande)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateDemande)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Checked)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Checked)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Plannr/Views/Book/Details.cshtml
@model Plannr.Models.DemandeReservation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>DemandeReservation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateDemande)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateDemande)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Checked)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Checked)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Plannr/Views/Book/Index.cshtml
@model IEnumerable<Plannr.Models.DemandeReservation>

@{
    ViewBag.Title = "Index";
}

@Html.Partial("_Index", Model);

Plannr/Views/Book/_BookCreate.cshtml
@model Plannr.Models.DemandeReservation
<div class="container-fluid">

    <div class="row-fluid">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Faire une demande de réservation</h5>
            </div>
            <div class="widget-content nopadding">

                @using (Html.BeginForm("Create", "Book", FormMethod.Post, new { @class = "form-horizontal", @id = "CreateDemandesForm" }))
                {
        
                    @Html.ValidationSummary(true)

  

                    <div class="control-group">
                        <label class="control-label" for="">@Html.LabelFor(model => model.Enseignement)</label>
                        <div class="controls">
                            @Html.DropDownListFor(model => model.Enseignement.Id, new SelectList(ViewBag.listEnseignements, "Id", "Libelle"))
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">@Html.LabelFor(model => model.BesoinProjecteur)</label>


                        <div class="controls">
                            @Html.EditorFor(model => model.BesoinProjecteur)
                            @Html.ValidationMessageFor(model => model.BesoinProjecteur)
                        </div>
                    </div>
        

                    <div class="control-group">
                        <label class="control-label">@Html.LabelFor(model => model.CapaciteNecessaire)</label>

                        <div class="controls">
                            @Html.EditorFor(model => model.CapaciteNecessaire)
                            @Html.ValidationMessageFor(model => model.CapaciteNecessaire)
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">@Html.LabelFor(model => model.DateVoulue)</label>

                        <div class="controls">
                            @Html.EditorFor(model => model.DateVoulue)
                            @Html.ValidationMessageFor(model => model.DateVoulue)
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">@Html.LabelFor(model => model.CreneauSouhaite)</label>
                        <div class="controls">
                            @Html.DropDownListFor(model => model.CreneauSouhaite.Id, new SelectList(ViewBag.listCreneauxHoraires, "Id", "HeureConcat"))
                        </div>
                    </div>


                    <div class="form-actions">
                        <input type="submit" value="Créer" class="btn btn-primary" />
                        <a href="@Url.Action("Index", "Book")" class="btn btn-danger" id="cancelEdit">Annuler</a>
                    </div>
     
                }

            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $("#DateVoulue").datepicker({
        dateFormat: "yy/mm/dd",
        firstDay:1
    })
</script>

Plannr/Views/Book/_BookList.cshtml
@model IEnumerable<Plannr.Models.DemandeReservation>


<div class="container-fluid">

    <div class="row-fluid">
        <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
								<span class="icon">
									<i class="icon-th"></i>
								</span>
                            <h5>Mes demandes de réservations</h5>
                        </div>
            <div class="widget-content nopadding">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Date demande  </th>
                    <th>Enseignement  </th>
                    <th>Date souhaitée  </th>
                    <th>Créneau </th>

                    <th>Capacité  </th>
                    <th>Projecteur</th>
                    <th>Statut  </th>
                    <th></th>

                </tr>
            </thead>

            <tbody id="listing">
            </tbody>

        </table>
        </div>
        @Scripts.Render("~/Scripts/Plannr/app/listingDemandes.js")
        <script type="text/javascript">
            demandesCollection.reset(@Html.Raw(@ViewBag.JSONModel))
        </script>

    </div>
    </div>
        </div>
</div>

Plannr/Views/Book/_Create.cshtml
@model Plannr.Models.DemandeReservation
<div id="content-header">
    <h1>Demandes de réservations</h1>
</div>
<div id="breadcrumb">
    <a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i>Home</a>
    <a href="#">Demandes de réservations</a>
    <a href="#" class="current">Création</a>
</div>

@Html.Partial("_BookCreate", Model)

Plannr/Views/Book/_Index.cshtml
@model IEnumerable<Plannr.Models.DemandeReservation>

<div id="demandesContainer">
    <div id="content-header">
        <h1>Demandes de réservations</h1>
    </div>
    <div id="breadcrumb">
        <a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i>Home</a>
        <a href="#">Demandes de réservations</a>
        <a href="#" class="current">Listing</a>
    </div>


    @Html.Partial("_BookList", Model)

    <center>
   <a href="@Url.Action("Create", "Book")" class="btn btn-large btn-primary" id="makeDemand"><i class="icon-pencil icon-white"></i> Faire une demande de réservation</a>
</center>
</div>


<div id="editContainer" style="display: none;">
</div>

<script type="text/javascript">

        var editLoaded = false;

        function showEdit() {
            $('#demandesContainer').fadeOut("fast", function () {
                $('#editContainer').fadeIn()
            })

        }

        function showDemandes() {
            $('#editContainer').fadeOut("fast", function () {
                $('#demandesContainer').fadeIn()
            })

        }

        $('#cancelEdit').live('click', function (e) {

            showDemandes()

            e.preventDefault()
            return false
        })

        $('#makeDemand').live('click', function (e) {
            if (!editLoaded) {
                $.get("@Url.Action("Create", "Book")", function (data) {

                    $('#editContainer').html(data)
                    showEdit()
                    editLoaded = true
                })

            } else {
                showEdit()
            }
            e.preventDefault()
            e.stopPropagation()
            return false
        })

     


</script>