Plannr/Models/Enseignement.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Plannr.Models
{
    public class Enseignement
    {
        [Key]
        public int Id {get;set;}

        // Navigators
        [JsonIgnore]
        public virtual Cours Cours { get; set; }
        [JsonIgnore]
        public virtual Enseignant Enseignant { get; set; }
        [JsonIgnore]
        public virtual Groupe Groupe { get; set; }
        // Helper method
        public string Libelle
        {
            get
            {
                if (this.Cours != null)
                {
                    return this.Cours.Libelle + " - " + this.Groupe.Libelle;
                }
                else
                {
                    return "";
                }
          
            }
        }

        

    }
}

Plannr/Controllers/EnseignementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plannr.Models;
using WebMatrix.WebData;
using System.Web.Security;
using Plannr.DAL;

namespace Plannr.Controllers
{
    public class EnseignementController : Controller
    {
        
        private PlannrContext db = new PlannrContext();
        private IEnseignantsRepository enseignantRepository;
        private ICoursRepository coursRepository;
        private IEnseignementsRepository enseignementRepository;
        //private IGroupeRepository coursRepository;

        public EnseignementController()
        {
            var context = new PlannrContext();
            enseignantRepository = new EnseignantsRepository(context);
            coursRepository = new CoursRepository(context);
            enseignementRepository = new EnseignementsRepository(context);
        }
        //
        // GET: /Enseignement/

        public ActionResult Index()
           {

               var id = (int)Membership.GetUser().ProviderUserKey;
               if (!Request.IsAjaxRequest())
               {
                   return View(this.enseignementRepository.GetEnseignementsForTeacher(id));
               }
               else
               {

                   return PartialView("_Index", this.enseignementRepository.GetEnseignementsForTeacher(id));
               } 
        }

        //
        // GET: /Enseignement/Details/5

        public ActionResult Details(int id = 0)
        {
            Enseignement enseignement = db.Enseignements.Find(id);
            if (enseignement == null)
            {
                return HttpNotFound();
            }
            return View(enseignement);
        }

        //
        // GET: /Enseignement/Create

        public ActionResult Create()
        {
            ViewBag.ListeCours = this.coursRepository.GetList();
            ViewBag.ListeEnseignants = this.enseignantRepository.GetList();
            ViewBag.ListeGroupes = db.Groupes.ToList();

            if (!Request.IsAjaxRequest())
            {
                return View();
            }
            else
            {

                return PartialView("_Create");
            } 
        }

        //
        // POST: /Enseignement/Create

        [HttpPost]
        public ActionResult Create(Enseignement enseignement)
        {
             enseignement.Enseignant = this.enseignantRepository.Get(enseignement.Enseignant.UserId);
            enseignement.Cours = this.coursRepository.Find(enseignement.Cours.Id);
           // enseignement.Cours = null;
            //enseignement.Groupe = db.Groupes.Find(enseignement.Groupe.Id);
            enseignement.Groupe.Libelle = "IG5";
            


            if (ModelState.IsValid)
            {
                this.enseignementRepository.Insert(enseignement);
                this.enseignementRepository.Save();
                return RedirectToAction("Index");
            }

            return View(enseignement);
        }

        //
        // GET: /Enseignement/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Enseignement enseignement = db.Enseignements.Find(id);
            if (enseignement == null)
            {
                return HttpNotFound();
            }
            return View(enseignement);
        }

        //
        // POST: /Enseignement/Edit/5

        [HttpPost]
        public ActionResult Edit(Enseignement enseignement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enseignement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enseignement);
        }

        //
        // GET: /Enseignement/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Enseignement enseignement = db.Enseignements.Find(id);
            if (enseignement == null)
            {
                return HttpNotFound();
            }
            return View(enseignement);
        }

        //
        // POST: /Enseignement/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Enseignement enseignement = db.Enseignements.Find(id);
            db.Enseignements.Remove(enseignement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Plannr/Views/Enseignement/Create.cshtml
@Html.Partial("_Create")

Plannr/Views/Enseignement/Delete.cshtml
@model Plannr.Models.Enseignement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Enseignement</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Libelle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Libelle)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Plannr/Views/Enseignement/Details.cshtml
@model Plannr.Models.Enseignement

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Enseignement</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Libelle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Libelle)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Plannr/Views/Enseignement/Edit.cshtml
@model Plannr.Models.Enseignement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Enseignement</legend>

        @Html.HiddenFor(model => model.Id)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Plannr/Views/Enseignement/Index.cshtml
@Html.Partial("_Index")

Plannr/Views/Enseignement/_Create.cshtml
@model Plannr.Models.Enseignement


@{
    ViewBag.Title = "Create";
}
<div id ="content-header">
<h1>Création</h1>
</div>
<div id="breadcrumb">
				<a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
				<a href="#" class="tip-bottom"> Administration</a>
                <a href="#" class="current">Gestion Enseignements</a>
                <a href="#" class="current">Creation Enseignement</a>
			</div>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <center>

    <fieldset>
        <legend> </legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Libelle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Libelle)
            @Html.ValidationMessageFor(model => model.Libelle)
        </div>
        <div class="control-group">
        <label class="control-label" for="">Cours</label>
         <div class="editor-field">
            @Html.DropDownListFor(model => model.Cours.Id, new SelectList(ViewBag.ListeCours, "Id", "Libelle"), "Sélectionnez un cours")  
           
        </div>
        </div>
        <div class="control-group">
        <label class="control-label" for="">Enseignant</label>
         <div class="editor-field">
            @Html.DropDownListFor(model => model.Enseignant.UserId, new SelectList(ViewBag.ListeEnseignants, "UserId", "UserName"), "Sélectionnez un enseignant")  
           
        </div>
        </div>
        <div class="control-group">
        <label class="control-label" for="">Groupe</label>
         <div class="editor-field">
            @Html.DropDownListFor(model => model.Groupe.Id, new SelectList(ViewBag.ListeGroupes, "Id", "Libelle"), "Sélectionnez un groupe")  
           
        </div>
        </div>

        <p><br /></p>

        <p>
            <input class="btn btn-large btn-primary" type="submit" value="Create"  />
            <a href="@Url.Action("Index", "Enseignement")" class="btn btn-large" id="cancelEdit">Annuler</a>
        </p>
    </fieldset>
    </center>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Plannr/Views/Enseignement/_Index.cshtml
@model IEnumerable<Plannr.Models.Enseignement>


@{
    ViewBag.Title = "Index";
}

<!--<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Libelle)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

@{
    ViewBag.Title = "IndexSalle";
}-->

<div id="choixContainer">
<div id ="content-header">
<h1>Gestion des enseignements</h1>
</div>
<div id="breadcrumb">
				<a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
				<a href="#" class="tip-bottom"> Gestion Enseignements</a>
                
			</div>



<div class="container-fluid">
    <div class="alert">
    <button class="close" data-dismiss="alert">×</button>
    
</div>
    <div class="row-fluid">
        <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
								<span class="icon">
									<i class="icon-th"></i>
								</span>
                            <h5>Liste des enseignements</h5>
                        </div>
            <div class="widget-content nopadding">
  <table class="table table-bordered">
    <tr >
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
         </th>
        <th>Cours</th>
        <th>Enseignant</th>
        <th>Groupe</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr >
        <td>
            @Html.DisplayFor(modelItem => item.Libelle)
            </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cours.Libelle)
            </td>
        <td>
            @Html.DisplayFor(modelItem => item.Enseignant.UserName)
            </td>
        <td>
            @Html.DisplayFor(modelItem => item.Groupe.Libelle)
            </td>
       
       
        <td>
            <center>
            <a href="@Url.Action("Delete", "Enseignement", new { id=item.Id })" class="btn btn-danger"><i class="icon-remove icon-white"></i></a>
            </center>
    </td>
    </tr>
}

</table>
        </div>
        

        

    </div>
    </div>
        </div>
</div>
<center>
<a href="@Url.Action("Create", "Enseignement")" class="btn btn-large btn-primary" id="add"><i class="icon-pencil icon-white"></i>Créer un nouvel enseignement</a>
</center>
    </div>

<div id="editContainer" style="display: none;">
</div>

<script type="text/javascript">

    var editLoaded = false;

    function showEdit() {
        $('#choixContainer').fadeOut("fast", function () {
            $('#editContainer').fadeIn()
            editLoaded = false;
        })

    }

    function showIndex() {
        $('#editContainer').fadeOut("fast", function () {
            $('#choixContainer').fadeIn()
            editLoaded = false;
        })

    }

    $('#cancelEdit').live('click', function (e) {

        showIndex()

        e.preventDefault()
        return false
    })

    $('#add').live('click', function (e) {
        if (!editLoaded) {
            $.get("@Url.Action("Create","Enseignement")", function (data) {

                $('#editContainer').html(data)
                showEdit()
                editLoaded = true
            })

        } else {
            showEdit()
        }
        e.preventDefault()
        e.stopPropagation()
        return false
    })

     </script>