Plannr/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plannr.Models;
using System.Web.Security;
using Plannr.DAL;
using Newtonsoft.Json;
using Plannr.Filters;
using WebMatrix.WebData;
using Microsoft.Web.WebPages.OAuth;

namespace Plannr.Controllers
{
    [Authorize(Roles = "Administrateur")]
    [InitializeSimpleMembership]
    public class AdministrationController : Controller
    {
        private PlannrContext db = new PlannrContext();
        private IEnseignantsRepository enseignantRepository;
        private ISallesRepository salleRepository;
        private IBatimentsRepository batimentRepository;
        private IMatieresRepository matiereRepository;
        private IUeRepository ueRepository;
        private IResponsableUe respRepository;

        //
        // GET: /Administration/

        public AdministrationController() {
            var context = new PlannrContext();
            enseignantRepository = new EnseignantsRepository(context);
            salleRepository = new SallesRepository(context);
            batimentRepository = new BatimentsRepository(context);
            matiereRepository = new MatieresRepository(context);
            ueRepository = new UeRepository(context);
            respRepository = new ResponsableUERepository(context);
        }

        public AdministrationController(IEnseignantsRepository repo, IBatimentsRepository batrepo, ISallesRepository salrepo, IMatieresRepository matrepo, IUeRepository uerepo, IResponsableUe resprepo)
        {
            this.enseignantRepository = repo;
            this.batimentRepository = batrepo;
            this.salleRepository = salrepo;
            this.matiereRepository = matrepo;
            this.ueRepository = uerepo;
            this.respRepository = resprepo;
        }

        //Administration's Index
        public ActionResult Index()
        {
            if (!Request.IsAjaxRequest())
            {
                return View();
            }
            else
            {
                
                return PartialView("_Index");
            }
               // return View();
            
        }

        //- - - - - - - - - - - - - - - - Enseignant - - - - - - - - - - - - - - - - - -

        //Enseignant's Index
        public ActionResult IndexEnseignant()
        {
            ViewBag.count = this.enseignantRepository.Count();
           

            if (!Request.IsAjaxRequest())
            {
                return View(this.enseignantRepository.GetList());
            }
            else
            {

                return PartialView("_IndexEnseignant", this.enseignantRepository.GetList());
            }
            
        }

        // GET: Administration/CreateEnseignant
        public ActionResult CreateEnseignant()
        {

            if (!Request.IsAjaxRequest())
            {
                
                return View();


            }
            else
            {
                System.Diagnostics.Debug.WriteLine("test2");
                return PartialView("_CreateEnseignant");
            }
        }

        //
        // POST: /Administration/Create

        [HttpPost]
        public ActionResult CreateEnseignant(Enseignant enseignant)
        {
            
            if (ModelState.IsValid)
            {

                this.enseignantRepository.Insert(enseignant);
                this.enseignantRepository.Save();
                Roles.AddUserToRole(enseignant.UserName, "Enseignant");
                WebSecurity.CreateAccount(enseignant.UserName, enseignant.UserName);

                
                return RedirectToAction("IndexEnseignant");
            }

            return View(enseignant);

        }

        // GET: /AddEnseignant/Edit

        public ActionResult EditEnseignant(int id = 0)
        {
            Enseignant enseignant = this.enseignantRepository.Get(id);
            System.Diagnostics.Debug.WriteLine("LALALA" + enseignant.UserId);

            if (enseignant == null)
            {System.Diagnostics.Debug.WriteLine("testedit0");
                return HttpNotFound();
            }
            else if (!Request.IsAjaxRequest())
            {
                System.Diagnostics.Debug.WriteLine("testedit1");
                return View(enseignant);
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("testedit");
                return PartialView("_EditEnseignant", enseignant);
            }
            
        }

        //
        // POST: /AddEnseignant/Edit

        [HttpPost]
        public ActionResult EditEnseignant(Enseignant enseignant)
        {

            System.Diagnostics.Debug.WriteLine("LALALA"+enseignant.UserId);
           // Enseignant e = this.enseignantRepository.GetEager(enseignant.UserId);
            //e.UserName = "salut";
            if (ModelState.IsValid)
            {
                this.enseignantRepository.Entry(enseignant);

                this.enseignantRepository.Save();
                return RedirectToAction("IndexEnseignant");
            }
            return View(enseignant);

        }
        
        

        // GET: /AddEnseignant/Delete

        public ActionResult DeleteEnseignant(int id = 0)
        {
            Enseignant enseignant = this.enseignantRepository.Get(id);
            if (enseignant == null)
            {
                return HttpNotFound();
            }
            else
            {
               // Membership.DeleteUser(enseignant.UserName);
               // Roles.RemoveUserFromRole(enseignant.UserName, "Enseignant");
               
                this.enseignantRepository.Delete(id);
                
                this.enseignantRepository.Save();
                return RedirectToAction("IndexEnseignant");
            }
           /* if (!Request.IsAjaxRequest())
            {
                return View(enseignant);
            }
            else
            {

                return PartialView("_DeleteEnseignant", enseignant);
            }*/

        }

        //
        // POST: /AddEnseignant/Delete

        [HttpPost, ActionName("DeleteEnseignant")]
        public ActionResult DeleteConfirmed(int id)
        {
            Enseignant ens = this.enseignantRepository.Get(id);
            this.enseignantRepository.Delete(id);
            
            this.enseignantRepository.Save();
            return RedirectToAction("IndexEnseignant");
        }

        // GET: /Administration/Details

        public ActionResult DetailsEnseignant(int id = 0)
        {
            Enseignant enseignant = this.enseignantRepository.Get(id);
            if (enseignant == null)
            {
                return HttpNotFound();
            }
            if (!Request.IsAjaxRequest())
            {
                return View(enseignant);
            }
            else
            {

                return PartialView("_DetailsEnseignant", enseignant);
            }

        }

        // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -



        //- - - - - - - - - - - - - - - - - Batiment - - - - - - - - - - - - - - - 
        //Batiment/Index
        public ActionResult IndexBatiment()
        {
            ViewBag.count = this.batimentRepository.Count();

            if (!Request.IsAjaxRequest())
            {
                return View(this.batimentRepository.GetAll());
            }
            else
            {
                return PartialView("_IndexBatiment", this.batimentRepository.GetAll());
            } 

        }


        // GET: /Administration/Create

        public ActionResult CreateBatiment(){
  
            if (!Request.IsAjaxRequest())
            {
                return View();
            }
            else
            {

                return PartialView("_CreateBatiment");
            } 

            }


        [HttpPost]
        public ActionResult CreateBatiment(Batiment batiment)
        {
            if (ModelState.IsValid)
            {
               
                    this.batimentRepository.Insert(batiment);
                    this.batimentRepository.Save();
                    return RedirectToAction("IndexBatiment");
                
            }

            return View(batiment);

        }

        // GET: /Salle/Details/5

        public ActionResult DetailsBatiment(int id = 0)
        {
          
            Batiment batiment = batimentRepository.Get(id);
            if (batiment == null)
            {
                return HttpNotFound();
            }
            if (!Request.IsAjaxRequest())
            {
                return View(batiment);
            }
            else
            {

                return PartialView("_DetailsBatiment", batiment);
            }

        }

        //Get
        public ActionResult EditBatiment(int id = 0)
        {
   
            Batiment batiment = batimentRepository.Get(id);
            if (batiment == null)
            {
                return HttpNotFound();
            }
            if (!Request.IsAjaxRequest())
            {
                return View(batiment);
            }
            else
            {

                return PartialView("_EditBatiment", batiment);
            }

        }

        [HttpPost]
        public ActionResult EditBatiment(Batiment batiment)
        {
            if (ModelState.IsValid)
            {

                batimentRepository.Entry(batiment);
                batimentRepository.Save();
                return RedirectToAction("IndexBatiment");
            }
            return View(batiment);
        }

        // GET: /Batiment/Delete/

        public ActionResult DeleteBatiment(int id = 0)
        {
   
            Batiment batiment = batimentRepository.Get(id);
            if (batiment == null)
            {
                return HttpNotFound();
            } 
            else

Plannr/Views/Administration/CreateMatiere.cshtml
﻿@model Plannr.Models.Matiere
@Html.Partial("_CreateMatiere")

Plannr/Views/Administration/CreateUE.cshtml
@Html.Partial("_CreateUE")

Plannr/Views/Administration/DeleteBatiment.cshtml
@Html.Partial("_DeleteBatiment")

Plannr/Views/Administration/DeleteEnseignant.cshtml
<<<<<<< HEAD
﻿@Html.Partial("_DeleteEnseignant")
=======
<<<<<<< HEAD
﻿@model Plannr.Models.Enseignant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Etes vous sûr de vouloir supprimer cet enseignant?</h3>
<fieldset>
    <legend>Enseignant</legend>

   <table class="table table-striped table-condensed">
  <thead>
              <tr style="background-color:#00A7C8; color:white">
                <th>@Html.DisplayNameFor(model => model.UserName)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.FirstName)</th>
                <th>@Html.DisplayNameFor(model => model.Tel)</th>
                
              </tr>
       <tr>
                <th>@Html.DisplayFor(model => model.UserName)</th>
                <th>@Html.DisplayFor(model => model.Name)</th>
                <th>@Html.DisplayFor(model => model.FirstName)</th>
                <th>@Html.DisplayFor(model => model.Tel)</th>
                
              </tr>
            </thead>

</table>
</fieldset>
@using (Html.BeginForm()) {
  
    <p>
        <input type="submit" value="Delete" class="btn btn-large btn-danger"/> |
        @Html.ActionLink("Back to List", "IndexEnseignant")
    </p>
}
=======
﻿@Html.Partial("_DeleteEnseignant") 
 
>>>>>>> parent of c08111b... Revert "ajout vues (3) pour thieeeeb"
>>>>>>> t4

Plannr/Views/Administration/DeleteMatiere.cshtml
<<<<<<< HEAD
﻿@Html.Partial("_DeleteMatiere")
=======
﻿@Html.Partial("_DeleteMatiere") 
 
>>>>>>> t4

Plannr/Views/Administration/EditBatiment.cshtml
@Html.Partial("_EditBatiment")

Plannr/Views/Administration/EditUE.cshtml
@Html.Partial("_EditUE")

Plannr/Views/Administration/Index.cshtml
@Html.Partial("_Index");

Plannr/Views/Administration/IndexBatiment.cshtml
@model IEnumerable<Plannr.Models.Batiment>

@{
    ViewBag.Title = "IndexBatiment";
}
@Html.Partial("_IndexBatiment")

Plannr/Views/Administration/IndexUE.cshtml
@model IEnumerable<Plannr.Models.Ue>

@{
    ViewBag.Title = "IndexUE";
}
@Html.Partial("_IndexUE")

Plannr/Views/Administration/_CreateMatiere.cshtml
@model Plannr.Models.Matiere


@{
    ViewBag.Title = "_CreateMatiere";
}

<div id ="content-header">
<h1>Création</h1>
</div>
<div id="breadcrumb">
				<a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
				<a href="#" class="tip-bottom"> Administration</a>
                <a href="#" class="current">Gestion Matieres</a>
                <a href="#" class="current">Creation Matiere</a>
			</div>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <center>

    <fieldset>
        <legend>Matière</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Libelle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Libelle)
            @Html.ValidationMessageFor(model => model.Libelle)
        </div>

         <div class="control-group">
        <label class="control-label" for="">@Html.LabelFor(model => model.Ue.Id)</label>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Ue.Id, new SelectList( ViewBag.uesList ,"Id", "Libelle"), "Sélectionnez une UE")
         </div>
        </div>
 


        <p>

            <input class="btn btn-large btn-primary" type="submit" value="Create"  />
            <a href="@Url.Action("IndexMatiere", "Administration")" class="btn btn-large" id="cancelEdit">Annuler</a>
        </p>
    </fieldset>
        </center>

}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Plannr/Views/Administration/_DetailsMatiere.cshtml
@model Plannr.Models.Matiere

@{
    ViewBag.Title = "_DetailsMatiere";
}

<div id ="content-header">
<h1>Details</h1>
</div>
<div id="breadcrumb">
				<a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
				<a href="#" class="tip-bottom"> Administration</a>
                <a href="#" class="current">Gestion Matieres</a>
                <a href="#" class="current">Details Matiere</a>
			</div>

<div class="container-fluid">
<div class="row-fluid">
        <div class="span12">
        <div class="widget-box">
            <div class="widget-content nopadding">
                
  <table class="table table-bordered">
    <tr >
                      
                <th>@Html.DisplayNameFor(model => model.Libelle)</th>
                 <th>@Html.DisplayNameFor(model => model.Ue)</th>
                
             
                
              </tr>
       <tr>
                
                <th>@Html.DisplayFor(model => model.Libelle)</th>
                <th>@Html.DisplayFor(model => model.Ue.Libelle)</th>
     
                
              </tr>
            </table>
        </div>
    </div>
    </div>
        </div>
    </div>


<center>
<p >
     <a href="@Url.Action("EditMatiere", "Administration", new { id=Model.Id })" class="btn btn-large btn-primary" >Edit</a> 
    <a href="@Url.Action("IndexMatiere", "Administration")" class="btn btn-large" id="cancelEdit">Annuler</a>
</p>
    </center>

Plannr/Views/Administration/_DetailsUE.cshtml
@model Plannr.Models.Ue

@{
    ViewBag.Title = "Details";
}

<div id ="content-header">
<h1>Details</h1>
</div>
<div id="breadcrumb">
				<a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
				<a href="#" class="tip-bottom"> Administration</a>
                <a href="#" class="current">Gestion UE</a>
                <a href="#" class="current">Details UE</a>
			</div>
<div class="container-fluid">
<div class="row-fluid">
        <div class="span12">
        <div class="widget-box">
            <div class="widget-content nopadding">
  <table class="table table-bordered">
    <tr >
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
  <th>@Html.DisplayNameFor(model => model.Description)</th>
    </tr>

    <tr >
        <th>
        @Html.DisplayFor(model => model.Libelle)

        </th>
        <th>
        @Html.DisplayFor(model => model.Description)

        </th>
    </tr>
</table>
        </div>
    </div>
    </div>
        </div>
    </div>

<center>
<p >
     <a href="@Url.Action("EditUE", "Administration", new { id=Model.Id })" class="btn btn-large btn-primary" >Edit</a> 
    <a href="@Url.Action("IndexUE", "Administration")" class="btn btn-large" id="cancelEdit">Annuler</a>
</p>
    </center>

Plannr/Views/Administration/_IndexEnseignant.cshtml
@model IEnumerable<Plannr.Models.Enseignant>

@{
    ViewBag.Title = "IndexEnseignant";
}

<div id="choixContainer">
<div id ="content-header">
<h1>Gestion des enseignants</h1>
</div>
<div id="breadcrumb">
				<a href="#" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
				<a href="#" class="tip-bottom"> Administration</a>
                <a href="#" class="current">Gestion Enseignant</a>
			</div>



<div class="container-fluid">
    <div class="alert">
    <button class="close" data-dismiss="alert">×</button>
    Il y a actuellement @ViewBag.count enseignant(s) recensé(s) dans la base de données.
</div>
    <div class="row-fluid">
        <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
								<span class="icon">
									<i class="icon-th"></i>
								</span>
                            <h5>Liste des enseignants</h5>
                        </div>
            <div class="widget-content nopadding">
  <table class="table table-bordered">
    <tr >
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    
    <tr >
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td ><center>
            <a href="@Url.Action("DetailsEnseignant", "Administration", new { id=item.UserId })"  class ="btn btn-success" id="detailsEns"><i class="icon-eye-open"></i>Détails</a>      
          
             </center>
        </td>
        <td>
            <center>
            <a href="@Url.Action("EditEnseignant", "Administration", new { id=item.UserId })" class="btn btn-primary" id="editEns"><i class="icon-pencil icon-white"></i>Editer</a>
            

            </center>
        </td>
        <td>
            <center>
            <a href="@Url.Action("DeleteEnseignant", "Administration", new { id=item.UserId })" class="btn btn-danger" ><i class="icon-remove icon-white"></i></a>
            </center>
    </td>
    </tr>
   
}

</table>
        </div>
        

        

    </div>
    </div>
        </div>
</div>
<center>
     
<a href="@Url.Action("CreateEnseignant", "Administration")" class="btn btn-large btn-primary" id="addEnseignant"><i class="icon-pencil icon-white"></i>Créer un nouvel enseignant</a>
</center>
    </div>

<div id="editContainer" style="display: none;">
</div>

<script type="text/javascript">

    var editLoaded = false;

    function showEdit() {
        $('#choixContainer').fadeOut("fast", function () {
            $('#editContainer').fadeIn()
            editLoaded = false;
        })

    }

    function showIndex() {
        $('#editContainer').fadeOut("fast", function () {
            $('#choixContainer').fadeIn()
            editLoaded = false;
        })

    }

    $('#cancelEdit').live('click', function (e) {

        showIndex()
        editLoaded = false;

        e.preventDefault()
        return false
    })

    $('#addEnseignant').live('click', function (e) {
        if (!editLoaded) {
            $.get("@Url.Action("CreateEnseignant","Administration")", function (data) {

                $('#editContainer').html(data)
                showEdit()
                editLoaded = true
            })

        } else {
            showEdit()
        }
         e.preventDefault()
         e.stopPropagation()
         return false
    })

  
    

     </script>